// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto

#include "service.pb.h"
#include "service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace service {

static const char* Dservice_method_names[] = {
  "/service.Dservice/upload",
};

std::unique_ptr< Dservice::Stub> Dservice::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Dservice::Stub> stub(new Dservice::Stub(channel, options));
  return stub;
}

Dservice::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_upload_(Dservice_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::service::FileChunk>* Dservice::Stub::uploadRaw(::grpc::ClientContext* context, ::service::Response* response) {
  return ::grpc::internal::ClientWriterFactory< ::service::FileChunk>::Create(channel_.get(), rpcmethod_upload_, context, response);
}

void Dservice::Stub::async::upload(::grpc::ClientContext* context, ::service::Response* response, ::grpc::ClientWriteReactor< ::service::FileChunk>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::service::FileChunk>::Create(stub_->channel_.get(), stub_->rpcmethod_upload_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::service::FileChunk>* Dservice::Stub::AsyncuploadRaw(::grpc::ClientContext* context, ::service::Response* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::service::FileChunk>::Create(channel_.get(), cq, rpcmethod_upload_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::service::FileChunk>* Dservice::Stub::PrepareAsyncuploadRaw(::grpc::ClientContext* context, ::service::Response* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::service::FileChunk>::Create(channel_.get(), cq, rpcmethod_upload_, context, response, false, nullptr);
}

Dservice::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Dservice_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< Dservice::Service, ::service::FileChunk, ::service::Response>(
          [](Dservice::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::service::FileChunk>* reader,
             ::service::Response* resp) {
               return service->upload(ctx, reader, resp);
             }, this)));
}

Dservice::Service::~Service() {
}

::grpc::Status Dservice::Service::upload(::grpc::ServerContext* context, ::grpc::ServerReader< ::service::FileChunk>* reader, ::service::Response* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace service

